version: '3.9'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  influxdb:
    image: influxdb:2.7
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpass
      - INFLUXDB_DB=smart_farm
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2

  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

  sensor-sim:
    build: ./sensor-sim
    depends_on:
      - ingestion
    environment:
      - GRPC_SERVER_ADDRESS=ingestion:50051

  ingestion:
    build: ./ingestion
    ports:
      - "50051:50051"
    depends_on:
      - kafka

  analytics:
    build: ./analytics
    depends_on:
      - kafka
      - influxdb

  actuator:
    build: ./actuator
    ports:
      - "50052:50052"   # actuator gRPC
      - "2112:2112"     # prometheus metrics endpoint
    depends_on:
      - prometheus

volumes:
  influxdb-data:
  grafana-data:
