// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.6.1
// source: actuator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PumpCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"` // "ON" or "OFF"
	SensorId      string                 `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PumpCommand) Reset() {
	*x = PumpCommand{}
	mi := &file_actuator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PumpCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PumpCommand) ProtoMessage() {}

func (x *PumpCommand) ProtoReflect() protoreflect.Message {
	mi := &file_actuator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PumpCommand.ProtoReflect.Descriptor instead.
func (*PumpCommand) Descriptor() ([]byte, []int) {
	return file_actuator_proto_rawDescGZIP(), []int{0}
}

func (x *PumpCommand) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PumpCommand) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

var File_actuator_proto protoreflect.FileDescriptor

const file_actuator_proto_rawDesc = "" +
	"\n" +
	"\x0eactuator.proto\x12\tsmartfarm\x1a\fsensor.proto\"B\n" +
	"\vPumpCommand\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x1b\n" +
	"\tsensor_id\x18\x02 \x01(\tR\bsensorId2F\n" +
	"\x0fActuatorService\x123\n" +
	"\aSetPump\x12\x16.smartfarm.PumpCommand\x1a\x0e.smartfarm.Ack\"\x00B3Z1github.com/fermat01/smart-farm-iot-platform/pb;pbb\x06proto3"

var (
	file_actuator_proto_rawDescOnce sync.Once
	file_actuator_proto_rawDescData []byte
)

func file_actuator_proto_rawDescGZIP() []byte {
	file_actuator_proto_rawDescOnce.Do(func() {
		file_actuator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_actuator_proto_rawDesc), len(file_actuator_proto_rawDesc)))
	})
	return file_actuator_proto_rawDescData
}

var file_actuator_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_actuator_proto_goTypes = []any{
	(*PumpCommand)(nil), // 0: smartfarm.PumpCommand
	(*Ack)(nil),         // 1: smartfarm.Ack
}
var file_actuator_proto_depIdxs = []int32{
	0, // 0: smartfarm.ActuatorService.SetPump:input_type -> smartfarm.PumpCommand
	1, // 1: smartfarm.ActuatorService.SetPump:output_type -> smartfarm.Ack
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_actuator_proto_init() }
func file_actuator_proto_init() {
	if File_actuator_proto != nil {
		return
	}
	file_sensor_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_actuator_proto_rawDesc), len(file_actuator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_actuator_proto_goTypes,
		DependencyIndexes: file_actuator_proto_depIdxs,
		MessageInfos:      file_actuator_proto_msgTypes,
	}.Build()
	File_actuator_proto = out.File
	file_actuator_proto_goTypes = nil
	file_actuator_proto_depIdxs = nil
}
